# Generated by Django 4.0.1 on 2022-01-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
