# Generated by Django 4.0.1 on 2022-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
